In [1]:
from imutils import face_utils
import numpy as np
import imutils
import dlib
import cv2

In [2]:
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('/home/amit/driver1/facial-landmarks/shape_predictor_68_face_landmarks.dat')

In [3]:
img = cv2.imread('Face9.jpg',0)
#img = imutils.resize(img, width=500)

In [4]:
cv2.imshow("Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
faces = detector(img,1)
print(faces)

rectangles[[(429, 123) (1809, 1503)]]


In [6]:
for (i, face) in enumerate(faces):
    shape = predictor(img, face)
    shape = face_utils.shape_to_np(shape)
    for (name, (j, k)) in face_utils.FACIAL_LANDMARKS_IDXS.items():
        (x, y, w, h) = cv2.boundingRect(np.array([shape[j:k]]))
        roi = img[y:y + h, x:x + w]
        roi = imutils.resize(roi, width=250, inter=cv2.INTER_CUBIC)
        if(j==36):
            right_eye = roi
        elif(j==42):
            left_eye = roi      

In [7]:
cv2.imshow("right_eye_first", right_eye)

cv2.waitKey(0)
cv2.destroyAllWindows()  

In [8]:
#pupil detection using cdf
img_flat = right_eye.flatten()

hist, bin_edges = np.histogram(img_flat, 256, [0,256])
pixel_prob = hist/img_flat.size

pixel_cmprob = np.zeros((256,1))
pixel_cmprob[0] = pixel_prob[0]

for i in range (1,256):
    pixel_cmprob[i] = pixel_cmprob[i-1] + pixel_prob[i]
    
new_img = np.zeros((right_eye.shape[0],right_eye.shape[1]))

min_arr = np.array([0,0])
for i in range(0, right_eye.shape[0]):
    for j in range(0, right_eye.shape[1]):
        if pixel_cmprob[right_eye[i,j]] < 0.06:
            new_img[i,j] = 255
        else:
            new_img[i,j] = 0
            
cv2.imshow("right_eye_first", new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()            

In [9]:
kernel = np.ones((2,2), np.uint8)
new_img_er1 = cv2.dilate(new_img, kernel, iterations=1)

In [10]:
cv2.imshow("Second", new_img_er1)
cv2.imshow("Original", right_eye)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
min_arr = np.array([0,0])
for i in range(0, right_eye.shape[0]):
    for j in range(0, right_eye.shape[1]):
        if(new_img_er1[i,j]==255):
            if(right_eye[i,j]<right_eye[min_arr[0], min_arr[1]]):
                min_arr[0] = i
                min_arr[1] = j

In [12]:
thresh_val1 = np.mean(right_eye[(min_arr[0]-5):(min_arr[0]+5), (min_arr[1]-5):(min_arr[1]+5)])
print(thresh_val1)         

31.57


In [13]:
right_eye_f1 = right_eye
_,right_eye_f1 = cv2.threshold(right_eye_f1, thresh_val1, 255, cv2.THRESH_BINARY_INV)
print(right_eye_f1)          

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
cv2.imshow("right_eye_f1", right_eye_f1)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
min_arr = np.array([0,0])
for i in range(0, right_eye.shape[0]):
    for j in range(0, right_eye.shape[1]):
        if(right_eye_f1[i,j]==255):
            if(right_eye[i,j]<right_eye[min_arr[0], min_arr[1]]):
                min_arr[0] = i
                min_arr[1] = j

In [16]:
thresh_val2 = np.mean(right_eye[(min_arr[0]-7):(min_arr[0]+7), (min_arr[1]-7):(min_arr[1]+7)])
print(thresh_val2) 

39.295918367346935


In [17]:
right_eye_f2 = right_eye
_,right_eye_f2 = cv2.threshold(right_eye_f2, thresh_val2, 255, cv2.THRESH_BINARY_INV)
print(right_eye_f2)          

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
cv2.imshow("right_eye_f2", right_eye_f2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
min_arr = np.array([0,0])
for i in range(0, right_eye_f2.shape[0]):
    for j in range(0, right_eye_f2.shape[1]):
        if(right_eye_f2[i,j]==255):
            if(right_eye[i,j]<right_eye[min_arr[0], min_arr[1]]):
                       min_arr[0] = i
                       min_arr[1] = j

In [20]:
print(min_arr[0],min_arr[1])

17 91


In [21]:
right_eye[min_arr[0], min_arr[1]]

20

In [22]:
right_eye2 = right_eye

In [23]:
cv2.circle(right_eye2, (min_arr[1],min_arr[0]), 30, (0,0,255), -1)

array([[190, 194, 194, ..., 100, 107, 111],
       [189, 190, 189, ...,  94, 100, 105],
       [190, 191, 190, ...,  91,  98, 102],
       ...,
       [145, 148, 152, ..., 108, 102, 109],
       [158, 153, 150, ..., 113, 110, 112],
       [155, 153, 153, ..., 115, 114, 116]], dtype=uint8)

In [24]:
cv2.imshow("right_eye2", right_eye2)

cv2.waitKey(0)
cv2.destroyAllWindows()